services:
  - type: web
    name: voting-system-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: AES_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://voting-system-frontend.vercel.app
      - key: API_URL
        value: https://voting-system-api.onrender.com

